//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Purchases = new HashSet<Purchase>();
        }

        public System.Guid product_ID { get; set; }
        [DisplayName("Product Name")]
        [Required]
        public string prod_name { get; set; }
        [DisplayName("Product Description")]
        [Required]
        public string prod_description { get; set; }
        [DisplayName("Product Price")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:0.00}")]
        [Required(ErrorMessage = "A Price between R 00.01 - R 9 999 999.99 is required!")]
        [RegularExpression(@"^\d+(.\d{1,2})?$", ErrorMessage = "A Price between R 00.01 - R 9 999 999.99 is required!")]
        [Range(0.01, 9999999.99, ErrorMessage = "A Price between R 00.01 - R 9 999 999.99 is required!")]
        public decimal prod_price { get; set; }
        public string prod_imgUrl { get; set; }
        [DisplayName("Image")]
        public HttpPostedFileBase File { get; set; }

        [Required(ErrorMessage = "An image is required"), FileExtensions(ErrorMessage = "Please upload an image file.")]
        public string FileName
        {
            get
            {
                if (File != null)
                    return File.FileName;
                else
                    return String.Empty;
            }
        }
        public Nullable<System.Guid> category_ID { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
