//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public System.Guid purchase_ID { get; set; }
        public System.Guid user_ID { get; set; }
        public System.Guid product_ID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
